// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otgzyaegisevvrunmagq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90Z3p5YWVnaXNldnZydW5tYWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxODY4NzIsImV4cCI6MjA1MTc2Mjg3Mn0.aOI4gUsgMej1OVn1mBF03M-gsD4bqi74LTXIbS2Km_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);